import {ExpressionLanguage} from "../index";
import PortabilityError from "../Semantics/PortabilityError";
import spec from "./fixtures/semantics-spec.json";
import fixture from "./fixtures/semantics-parity.json";

/**
 * Every operator applied to every pair of operands of semantics-spec.json (numbers, numeric and non-numeric strings, null,
 * booleans, arrays, hashes...) was evaluated by Symfony's own code: semantics-parity.json holds its answers, generated by
 * scripts/generate-semantics-fixtures.php. The default "symfony" semantics have to give the same ones.
 *
 * The "portable" semantics are then checked against the two others: they give the result both agree on, and fail where they do not.
 */

// the same expansion as scripts/generate-semantics-fixtures.php
function expand() {
    const cases = [];
    for (const operator of spec.binary) {
        for (const left of spec.values) {
            for (const right of spec.values) {
                cases.push([`a ${operator} b`, {a: left, b: right}]);
            }
        }
    }
    for (const operator of spec.unary) {
        for (const value of spec.values) {
            cases.push([`${operator}a`, {a: value}]);
        }
    }
    for (const expression of spec.other) {
        for (const value of spec.values) {
            cases.push([expression, {a: value, b: value}]);
        }
    }

    return cases;
}

const cases = expand();

function outcome(language, expression, variables) {
    try {
        return {value: language.evaluate(expression, JSON.parse(JSON.stringify(variables)))};
    } catch (e) {
        return {error: `${e.name}: ${e.message}`, errorName: e.name};
    }
}

// PHP has no -0 integer, an empty array is an empty hash, and INF / NAN need a spelling
function normalize(value) {
    if (typeof value === 'number') {
        if (!Number.isFinite(value)) {
            return {$special: Number.isNaN(value) ? 'NaN' : (value > 0 ? 'Infinity' : '-Infinity')};
        }

        return Object.is(value, -0) ? 0 : value;
    }
    if (Array.isArray(value)) {
        return value.map(normalize);
    }
    if (value !== null && typeof value === 'object') {
        const keys = Object.keys(value);

        return keys.length === 0 ? [] : Object.fromEntries(keys.map((key) => [key, normalize(value[key])]));
    }

    return value;
}

// the last digit of a power can differ by one unit: V8 and libm do not round pow() alike
const closeEnough = (a, b) => typeof a === 'number' && typeof b === 'number' && Math.abs(a - b) <= 1e-14 * Math.max(1, Math.abs(a), Math.abs(b));

// `~` on a string complements its bytes, which gives bytes that are not UTF-8: PHP's own JSON cannot even write them
const isBytewiseNot = (expression, variables) => expression === '~a' && typeof variables.a === 'string';

test('the fixture matches the spec', () => {
    expect(fixture.results).toHaveLength(cases.length);
    expect(cases.length).toBeGreaterThan(10000);
});

test('the default semantics give the results and the errors of Symfony for every operator and every pair of operands', () => {
    const language = new ExpressionLanguage();
    const differences = [];

    cases.forEach(([expression, variables], index) => {
        if (isBytewiseNot(expression, variables)) {
            return;
        }

        const expected = fixture.results[index];
        const actual = outcome(language, expression, variables);

        if (typeof expected === 'number') {
            if (actual.error !== fixture.messages[expected]) {
                differences.push({expression, variables, symfony: fixture.messages[expected], ours: actual.error ?? actual.value});
            }

            return;
        }

        const [wanted] = expected;
        if ('error' in actual || (!closeEnough(actual.value, wanted) && JSON.stringify(normalize(actual.value)) !== JSON.stringify(normalize(wanted)))) {
            differences.push({expression, variables, symfony: wanted, ours: actual.error ?? actual.value});
        }
    });

    expect(differences).toEqual([]);
});

test('the portable semantics give what the Symfony and the JavaScript ones agree on, and fail where they do not', () => {
    const symfony = new ExpressionLanguage(null, [], {semantics: 'symfony'});
    const js = new ExpressionLanguage(null, [], {semantics: 'js'});
    const portable = new ExpressionLanguage(null, [], {semantics: 'portable'});
    const differences = [];
    let agreed = 0;
    let refused = 0;

    // Whether both sets of rules answer a condition alike: portable refuses at that step, even if the end result would coincide
    // ("0" and 0 is false for both, but they disagree on "0" being true)
    const agreeOnTruth = (value) => {
        const fromSymfony = outcome(symfony, '!a', {a: value});
        const fromJs = outcome(js, '!a', {a: value});

        return fromSymfony.value === fromJs.value;
    };
    const truth = (value) => outcome(symfony, '!!a', {a: value}).value;
    const refusal = {errorName: 'PortabilityError'};

    // the outcome that "portable" has to give
    const expectedOutcome = (expression, variables, fromSymfony, fromJs) => {
        const {a, b} = variables;
        switch (expression) {
            case 'a and b':
                if (!agreeOnTruth(a)) return refusal;
                if (!truth(a)) return {value: false};
                return agreeOnTruth(b) ? {value: truth(b)} : refusal;
            case 'a or b':
                if (!agreeOnTruth(a)) return refusal;
                if (truth(a)) return {value: true};
                return agreeOnTruth(b) ? {value: truth(b)} : refusal;
            case 'a xor b':
                return agreeOnTruth(a) && agreeOnTruth(b) ? fromSymfony : refusal;
            case 'a ? 1 : 2':
            case 'a ?: 2':
            case 'a ? a : 2':
            case '!a':
            case 'not a':
                return agreeOnTruth(a) ? fromSymfony : refusal;
            case 'a ?? 2':
                return fromSymfony;
        }

        if ('error' in fromSymfony && 'error' in fromJs) {
            return fromSymfony;
        }
        if (!('error' in fromSymfony) && !('error' in fromJs) && JSON.stringify(normalize(fromSymfony.value)) === JSON.stringify(normalize(fromJs.value))) {
            return fromSymfony;
        }

        return refusal;
    };

    cases.forEach(([expression, variables]) => {
        if (isBytewiseNot(expression, variables)) {
            return;
        }

        const expected = expectedOutcome(expression, variables, outcome(symfony, expression, variables), outcome(js, expression, variables));
        const actual = outcome(portable, expression, variables);

        const matches = 'errorName' in expected
            ? actual.errorName === expected.errorName
            : (actual.errorName === undefined && JSON.stringify(normalize(actual.value)) === JSON.stringify(normalize(expected.value)));

        if (expected === refusal) {
            refused++;
        } else {
            agreed++;
        }
        if (!matches) {
            differences.push({expression, variables, expected: expected.error ?? expected.value ?? expected.errorName, portable: actual.error ?? actual.value});
        }
    });

    expect(differences).toEqual([]);
    // both outcomes are well represented, otherwise the matrix proves little
    expect(agreed).toBeGreaterThan(3000);
    expect(refused).toBeGreaterThan(3000);
});

test('a PortabilityError names the operator, the operands and both results', () => {
    const portable = new ExpressionLanguage(null, [], {semantics: 'portable'});

    expect(() => portable.evaluate('"5" + 1')).toThrow(PortabilityError);
    expect(() => portable.evaluate('"5" + 1')).toThrow('"+" is not portable: with "5" and 1, PHP gives 6 and JavaScript gives "51".');
    expect(() => portable.evaluate('a == b', {a: null, b: false})).toThrow('"==" is not portable: with null and false, PHP gives true and JavaScript gives false.');
    expect(() => portable.evaluate('a ? 1 : 2', {a: '0'})).toThrow('"boolean test" is not portable: with "0", PHP gives false and JavaScript gives true.');
    expect(() => portable.evaluate('"abc" + 1')).toThrow('PHP gives TypeError: Unsupported operand types: string + int and JavaScript gives "abc1".');
});
