import {ExpressionLanguage} from "../index";
import corpus from "./fixtures/symfony-corpus.json";
import expected from "./fixtures/symfony-parity.json";

/**
 * Replays src/__tests__/fixtures/symfony-corpus.json through this library and compares the outcome with what
 * Symfony's own ExpressionLanguage produced for the very same expressions (symfony-parity.json, generated by
 * scripts/generate-parity-fixtures.php). A failure here means this library drifted away from Symfony.
 *
 * Expressions that are deliberately not compared are listed below with the reason.
 */
const KNOWN_DIFFERENCES = {
    // the text of the regex engines' own error messages
    "'a' matches '/(/'": 'PCRE vs RegExp error text',
    "'a' matches 'a'": 'PCRE vs RegExp error text',
    "'a' matches ''": 'PCRE vs RegExp error text',
    "'a' matches 5": 'PHP casts the number to a string before validating it',
    // PHP distinguishes arrays from objects (and from strings) where JavaScript only has objects
    '[1] contains 1': 'an array is a TypeError for str_contains()',
    'a["b"]': 'an object is not an array in PHP',
    'a.b()': 'the class name of a plain object is "stdClass" in PHP',
    // PHP juggles a non-numeric string to 0
    '"a"..3': 'range() type juggling',
};

function run(el, expression, variables) {
    try {
        return {result: el.evaluate(expression, variables)};
    } catch (e) {
        return {error: e.message};
    }
}

function normalize(value) {
    if (typeof value === 'number' && !Number.isFinite(value)) {
        return {$special: Number.isNaN(value) ? 'NaN' : (value > 0 ? 'Infinity' : '-Infinity')};
    }
    if (Array.isArray(value)) {
        return value.length === 0 ? [] : value.map(normalize);
    }
    if (value !== null && typeof value === 'object') {
        const keys = Object.keys(value);
        if (keys.length === 0) {
            return [];
        }
        return Object.fromEntries(keys.map((k) => [k, normalize(value[k])]));
    }

    return value;
}

test('the corpus and its Symfony results line up', () => {
    expect(expected).toHaveLength(corpus.length);
});

test('this library gives the same results and error messages as Symfony for the shared corpus', () => {
    const el = new ExpressionLanguage();
    const differences = [];

    corpus.forEach(([expression, variables], index) => {
        const symfony = expected[index];
        if ('warning' in symfony || KNOWN_DIFFERENCES[expression] !== undefined) {
            return;
        }

        const ours = run(el, expression, JSON.parse(JSON.stringify(variables)));

        if ('error' in symfony) {
            if (ours.error !== symfony.error) {
                differences.push({expression, variables, symfony: symfony.error, ours: 'error' in ours ? ours.error : ours.result});
            }
            return;
        }

        let actual = 'error' in ours ? {$error: ours.error} : normalize(ours.result);
        let wanted = normalize(symfony.result);
        // preg_match() gives 1/0 where we give a boolean
        if (typeof actual === 'boolean' && typeof wanted === 'number') {
            actual = Number(actual);
        }

        try {
            expect(actual).toEqual(wanted);
        } catch (e) {
            differences.push({expression, variables, symfony: wanted, ours: actual});
        }
    });

    expect(differences).toEqual([]);
});
